### ISSUE TITLE
How options are supposed to work?

### ISSUE THREAD

**Issue by YakovL** [hfalucas/vue-simplebar#1]
Hi, I'm trying to use vue-simplebar and while the default one works for me like this:
in template:

    <SimpleBar class="examinations">
        <ExaminationList />
    </SimpleBar>

in script:

    import SimpleBar from 'simplebar-vue';
    import 'simplebar/dist/simplebar.min.css';
    //...
        components: {
            //...
            SimpleBar,
        }

I fail to set custom options. To be precise, I've only succeeded to set direction like this:

    <SimpleBar class="examinations" data-simplebar data-simplebar-direction="rtl">
        <ExaminationList />
    </SimpleBar>

but it doesn't work like this

    <SimpleBar class="examinations" :options="{ direction: 'rtl' }">
        <ExaminationList />
    </SimpleBar>

and for autoHide or scrollbarMinSize all these don't seem to work:

    <SimpleBar class="examinations" :options="{ autoHide: false }">
        <ExaminationList />
    </SimpleBar>

    <SimpleBar class="examinations" data-simplebar data-simplebar-autoHide="false">
        <ExaminationList />
    </SimpleBar>

    <SimpleBar class="examinations" data-simplebar data-simplebar-auto-hide="false">
        <ExaminationList />
    </SimpleBar>

Is this a bug? Am I missing something? Would be nice to have usage of options described in docs explicitly.

Best regards

**Comment by hfalucas** [comment]
Hello @YakovL,

By the examples, it seems that you are using [SimpleBar Vue](https://github.com/Grsmto/simplebar/tree/master/examples/vue) instead of this package (Vue SimpleBar).

If you want to use this package you can pass options like this:
```
<template>
    <vue-simplebar :options="{autoHide: false, direction: 'rtl'}">
        <p> Your scrollable content goes here. </p>
    </vue-simplebar>
</template>

<script>
import { VueSimplebar } from 'vue-simplebar'
export default {
    components: { VueSimplebar }
}
</script>

<style src="vue-simplebar/dist/vue-simplebar.css"/>
```

**Comment by YakovL** [comment]
ah, right, that was confusing. Thanks! I've "re"nstalled Vue SimpleBar instead of SimpleBar Vue, `autoHide` works this way indeed, but `direction` doesn't work for some reason. Any ideas?

Also, I've noticed a couple of issues to be reported separately: `Unable to preventDefault inside passive event listener invocation.` errors in console on each ~mousedown on scrollbar and also unlike SimpleBar Vue, Vue SimpleBar doesn't seem to get updated with `vue-cli-service serve` when I change options in template, I have to manually reload the page.

**Comment by hfalucas** [comment]
After some digging in the official package found out the `direction` option seems to be applied only if the [`data-simplebar-direction`](https://github.com/Grsmto/simplebar/blob/master/packages/simplebar/src/simplebar.css#L182) attribute is present in the HTML. I guess for that option, in particular, you'll need to declare specifically on the element as `data` attribute 🤷‍♂️. 

```
// JS
<vue-simplebar id="scroller" data-simplebar-direction="rtl" :options="{autoHide: false}">
    <p> Your scrollable content goes here. </p>
</vue-simplebar>

// CSS
#scroller {
  direction: rtl;
}
```

You can try and open an issue on the [official repository](https://github.com/Grsmto/simplebar/tree/master/examples/vue) and state that `direction option` has no effect if passed in the initialization object, I believe there's not much I can do about that on my side.

About the other issues:
- **Unable to preventDefault inside passive event listener invocation.**
I can't seem to reproduce this. Which browser are you using, can you provide a simple fiddle?

- **Hot Reload with vue-cli-service serve**
Haven't used it, will try to take a look at it this weekend and see what happens

**Comment by YakovL** [comment]
Right, thanks. Will be cool if you add this quirk about options into readme

Regarding "Unable to preventDefault inside passive event listener invocation": I get this in both Vivaldi (Chromium-based) and Chrome; regarding a fiddle.. stackblitz.com doesn't seem to support Vue, are you aware of a simple way to create a service with the necessary bits (Vue, Vue SimpleBar, dependencies?)
