### ISSUE TITLE
How to use methods, either getScrollElement or something to scroll element programmatically?

### ISSUE THREAD

**Issue by YakovL** [hfalucas/vue-simplebar#2]
I'm using vue-simplebar in a component that shows some paginated list. I noticed that on changing the page, the scroll stays where it were, but user would probably expect that the list gets scrolled to the top on page change.

I'm looking for a way to scroll the list programmatically. The problem is: I don't understand how to get the corresponding `SimpleBar` instance from a component so that I can call one of its methods. For instance, I could use

    const scrollElement = simpleBar.getScrollElement();
    scrollElement.scrollTo(0, 0);

if I had reference to `scrollElement` but I don't understand if I can get it.

The only workaround I can think of is to grab the element using some selector.. actually, after several experiments with inspector and console I figured that currently I can do

    document.querySelector('.simplebar-content-wrapper').scrollTo(0,0)

to achieve this (well, it should be scoped to the component instead of looking through the whole document), but there's no garantee that the correct selector won't change (`getScrollElement` should get the correct element), so still it would be nice to be able to get the `SimpleBar` instance/call its methods. Any ideas?

**Comment by hfalucas** [comment]
Simply grab a reference of the component and you are able to use the helper methods
```
<vue-simplebar ref="scroll">
 // content
</vue-simplebar>

// Goes to the top of container - Y Axis
this.$refs.scroll.scrollTop() 

// Goes to the bottom of container - Y Axis
this.$refs.scroll.scrollBottom() 

// Scrolls 40px from the top of the container - Y Axis
this.$refs.scroll.scrollto(40) 

```

**Comment by YakovL** [comment]
Nice, thanks!

**Comment by sinzo** [comment]
I get this error "Uncaught TypeError: Cannot read property 'scrollto' of undefined" when call refs. I just want simple scroll to the top once click the item inside simplebar

this is my code

```
<simplebar  class="c-section__map-scroll" data-simplebar-auto-hide="false" ref="scroll"> iterate items... </simplebar>

mounted: function () { 
   var vm = this 
   $(".c-listingmap .c-listingmap__item").on("click", function() {
                $('.c-listingmap .c-listingmap__item').removeClass("active");
                $(this).addClass("active");

                vm.$refs.scroll.scrollto(50) 

            });
}
```

**Comment by YakovL** [comment]
I can't help asking why you are using jQuery where you can use Vue only? Not sure why are you having this issue, but messing with mounted may cause problems (`$refs` [are](https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements) only populated after the component has been rendered, and they are not reactive)

**Comment by hfalucas** [comment]
@sinzo Are you importing the plugin correctly? I also have the same question, why not just use Vue instead? Can you make a simple fiddle reproducing the issue?

**Comment by sinzo** [comment]
Sorry just notice that I'm using "simplebar-vue" and i've have fix my issue using methods.
