### ISSUE TITLE
Nothing displays when slotted content updates

### ISSUE THREAD

**Issue by Erutan409** [hfalucas/vue-simplebar#3]
Is this expected behavior?  I'm extending your component and attempting to force it to take into account updates:

```vue
<script>

    import {VueSimplebar} from "vue-simplebar";

    const reInit = VueSimplebar.mounted;

    export default {
        extends: VueSimplebar,
        beforeUpdate() {
            this.destroy();
        },
        updated() {
            reInit.call(this);
        }
    }

</script>

<style lang="scss">

    @import "~simplebar/src/simplebar.css";

</style>
```

However, this doesn't seem to fix the problem.  I can confirm that my slotted content is in the component.  But, the plugin isn't re-applied.

This is an example of what I'm using inside this component:

```vue
<scrollbar
    class="question"
    :style="style.container"
    tag="ul"
    :options="scrollbarSettings"
>
    <li
        :class="{selected: selected.question === item}"
        :key="index"
        @click="selectQuestion(item)"
        v-for="(item, index) in renderedQuestions"
    >
        <i class="fas fa-chevron-right"></i> {{ item.recordTitle }}
    </li>
    <li
        class="placeholder no-hover no-border no-underline no-transition"
        v-if="!this.renderedQuestions.length"
    >
        Please select a topic
    </li>
</scrollbar>
```

**Comment by hfalucas** [comment]
Can you try to wrap the slot content in a parent element that doesn't change?
```vue
<scrollbar>
    <ul>
        <li v-for="(item, index) in items">...</li>
    </ul>
</scrollbar>
```
This simple solution avoids unnecessary DOM updates.

**Comment by Erutan409** [comment]
@hfalucas This sort of fixes the issue.  Now I'm having an issue with the scrollbar being excessively long and the parent container (your component) not being properly constrained to the desired height.  I'm assuming it's a CSS update on my end, though.

I'll report back once I have it dialed in to confirm the overall solution.

**Comment by Erutan409** [comment]
@hfalucas Fixed on my end.  Your suggestion was the route I was going to end up with.  The solution makes more sense, but I was also hoping I wouldn't need to as much refactoring for my styling.  But, either way - thank you.

**Comment by hfalucas** [comment]
Glad you sorted it out, and sorry for the extra work.

**Comment by Erutan409** [comment]
No worries.  Thank you for the quick response and the package.  I like this better than the official one, since I can extend yours and build it.  Well, more straightforward, anyway.
